services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: cs2_battle_bot_api
    command: sh -c "cd src && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8002:8000"
    volumes:
      - ./:/app/
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - cs2-battle-bot-network
  db:
    image: postgres:15.1
    container_name: cs2_battle_bot_db
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5435:5432"
    healthcheck:
      test: "exit 0"
    networks:
      - cs2-battle-bot-network
  redis:
    image: "redis:alpine"
    container_name: cs2_battle_bot_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    expose:
      - "6379:6379"
    networks:
      - cs2-battle-bot-network
    healthcheck:
      test: "exit 1"

networks:
  cs2-battle-bot-network:
    external: true
