services:
  app:
    build: ./
    container_name: discord_cs2_mm_app
    # command: gunicorn tf2_api.wsgi:application --bind 0.0.0.0:8000 --reload
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8002:8000"
    volumes:
      - ./:/app/
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    networks:
      - discord-cs2-mm-network
  db:
    image: postgres:15.1
    container_name: discord_cs2_mm_db
    environment:
      - POSTGRES_DB=cs2_db
      - POSTGRES_USER=cs2_user
      - POSTGRES_PASSWORD=cs2_password
    restart: always
    ports:
      - "5435:5432"
    healthcheck:
      test: "exit 0"
    networks:
      - discord-cs2-mm-network
  redis:
    image: "redis:alpine"
    container_name: discord_cs2_mm_redis
    restart: always
    expose:
      - "6379:6379"
    networks:
      - discord-cs2-mm-network
    healthcheck:
      test: "exit 1"

networks:
  discord-cs2-mm-network:
    external: true