### Create match
GET http://localhost:8002/api/matches/

### Create match
POST https://cs2.sharkservers.pl/api/matches/
Content-Type: application/json

{
    "discord_users_ids": ["264857503974555649", "264857503974555649", "264857503974555649"],
    "team1_name": "Virtus Pro",
    "map_list": ["de_mirage"]
}

### Start match
PUT http://localhost:8002/api/matches/start/
Content-Type: application/json


### End kniferound
PUT http://localhost:8002/api/matches/end_knife_round/
Content-Type: application/json

{
    "winner": "ct",
    "site": "t"
}

### Ban map
POST http://localhost:8002/api/servers/create_match/
Content-Type: application/json

{
    "team_one_id": "1",
    "team_two_id": "2",
}