name: Publish Backend Docker image

on:
    release:
        types: [ published ]


jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest

        steps:
            -   name: Check out the repo
                uses: actions/checkout@v4.1.1

            -   name: Log in to Docker Hub
                uses: docker/login-action@v3.0.0
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Extract metadata (tags, labels) for Docker
                id: meta
                uses: docker/metadata-action@v5.5.1
                with:
                    images: qwizii/cs2-battle-bot-api

            -   name: Build and push Docker image
                uses: docker/build-push-action@v5.1.0
                with:
                    context: ./src/
                    file: ./src/Dockerfile
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
            -   name: Discord notification
                env:
                    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
                uses: Ilshidur/action-discord@master
                with:
                    args: '{{ EVENT_PAYLOAD.repository.full_name }} successfully built and pushed Docker image.'
